name: cancellable_process
description: Provides an easy way to retry asynchronous functions. The delay and asynchronous functions you will give are repeated according to the maximum number of repetitions you will give, and the answer is returned as an error or correct result. Error handling is provided using the Either package.
version: 0.0.5
homepage: "https://github.com/endmr11/cancellable_process"

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  either_dart: ^0.4.0
  async: ^2.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
