name: cancellable_process
description: Provides an easy way to retry asynchronous functions.
version: 0.0.3
homepage: "https://github.com/endmr11/cancellable_process"

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  either_dart: ^1.0.0
  async: ^2.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
